"""add notifications

Revision ID: 13ea5fa34ae6
Revises: f8d630fce227
Create Date: 2026-07-13 18:58:18.128126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ea5fa34ae6'
down_revision: Union[str, Sequence[str], None] = 'f8d630fce227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_table', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_response', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_notifications_created_by'), 'notifications', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_deleted_by'), 'notifications', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notifications_updated_by'), 'notifications', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_notifications_priority', 'notifications', ['priority'], unique=False, schema='core')
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False, schema='core')
    op.create_table('notification_users',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['core.notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_notification_users_created_by'), 'notification_users', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notification_users_deleted_by'), 'notification_users', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_notification_users_updated_by'), 'notification_users', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_notification_status', 'notification_users', ['status'], unique=False, schema='core')
    op.create_index('ix_notification_user', 'notification_users', ['notification_id', 'user_id'], unique=True, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_user', table_name='notification_users', schema='core')
    op.drop_index('ix_notification_status', table_name='notification_users', schema='core')
    op.drop_index(op.f('ix_core_notification_users_updated_by'), table_name='notification_users', schema='core')
    op.drop_index(op.f('ix_core_notification_users_deleted_by'), table_name='notification_users', schema='core')
    op.drop_index(op.f('ix_core_notification_users_created_by'), table_name='notification_users', schema='core')
    op.drop_table('notification_users', schema='core')
    op.drop_index('ix_notifications_status', table_name='notifications', schema='core')
    op.drop_index('ix_notifications_priority', table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_updated_by'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_deleted_by'), table_name='notifications', schema='core')
    op.drop_index(op.f('ix_core_notifications_created_by'), table_name='notifications', schema='core')
    op.drop_table('notifications', schema='core')
    # ### end Alembic commands ###
