"""test

Revision ID: 1caa5fe27ba0
Revises: c76f4e514671
Create Date: 2026-07-14 17:37:18.412668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1caa5fe27ba0'
down_revision: Union[str, Sequence[str], None] = 'c76f4e514671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_jti', sa.String(length=36), nullable=False),
    sa.Column('refresh_jti', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_sessions_created_by'), 'user_sessions', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_sessions_deleted_by'), 'user_sessions', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_user_sessions_updated_by'), 'user_sessions', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_user_sessions_access_jti', 'user_sessions', ['access_jti'], unique=True, schema='core')
    op.create_index('ix_user_sessions_refresh_jti', 'user_sessions', ['refresh_jti'], unique=True, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_refresh_jti', table_name='user_sessions', schema='core')
    op.drop_index('ix_user_sessions_access_jti', table_name='user_sessions', schema='core')
    op.drop_index(op.f('ix_core_user_sessions_updated_by'), table_name='user_sessions', schema='core')
    op.drop_index(op.f('ix_core_user_sessions_deleted_by'), table_name='user_sessions', schema='core')
    op.drop_index(op.f('ix_core_user_sessions_created_by'), table_name='user_sessions', schema='core')
    op.drop_table('user_sessions', schema='core')
    # ### end Alembic commands ###
