"""Initial Core

Revision ID: 8c2c063349bb
Revises: 
Create Date: 2026-07-12 21:12:12.253410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c2c063349bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_index(op.f('ix_core_document_types_code'), 'document_types', ['code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_document_types_created_by'), 'document_types', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_document_types_deleted_by'), 'document_types', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_document_types_updated_by'), 'document_types', ['updated_by'], unique=False, schema='core')
    op.create_table('genders',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_index(op.f('ix_core_genders_code'), 'genders', ['code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_genders_created_by'), 'genders', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_genders_deleted_by'), 'genders', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_genders_updated_by'), 'genders', ['updated_by'], unique=False, schema='core')
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_index(op.f('ix_core_permissions_code'), 'permissions', ['code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_permissions_created_by'), 'permissions', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_permissions_deleted_by'), 'permissions', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_permissions_updated_by'), 'permissions', ['updated_by'], unique=False, schema='core')
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_index(op.f('ix_core_roles_code'), 'roles', ['code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_roles_created_by'), 'roles', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_roles_deleted_by'), 'roles', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_roles_updated_by'), 'roles', ['updated_by'], unique=False, schema='core')
    op.create_table('people',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('document_number', sa.String(length=30), nullable=False),
    sa.Column('gender_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['core.document_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gender_id'], ['core.genders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_people_created_by'), 'people', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_people_deleted_by'), 'people', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_people_email'), 'people', ['email'], unique=False, schema='core')
    op.create_index(op.f('ix_core_people_updated_by'), 'people', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_people_document', 'people', ['document_type_id', 'document_number'], unique=True, schema='core')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions'),
    schema='core'
    )
    op.create_index('ix_role_permissions_permission', 'role_permissions', ['permission_id'], unique=False, schema='core')
    op.create_index('ix_role_permissions_role', 'role_permissions', ['role_id'], unique=False, schema='core')
    op.create_table('users',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('last_login_user_agent', sa.String(length=500), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['core.people.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_created_by'), 'users', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_deleted_by'), 'users', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_person_id'), 'users', ['person_id'], unique=True, schema='core')
    op.create_index(op.f('ix_core_users_updated_by'), 'users', ['updated_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_username'), 'users', ['username'], unique=True, schema='core')
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False, schema='core')
    op.create_index('ix_audit_logs_record', 'audit_logs', ['entity_id'], unique=False, schema='core')
    op.create_index('ix_audit_logs_table', 'audit_logs', ['table_name'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_created_by'), 'audit_logs', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_deleted_by'), 'audit_logs', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_logs_updated_by'), 'audit_logs', ['updated_by'], unique=False, schema='core')
    op.create_table('files',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('entity_table', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['core.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_files_created_by'), 'files', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_files_deleted_by'), 'files', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_files_updated_by'), 'files', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_files_entity', 'files', ['entity_table', 'entity_id'], unique=False, schema='core')
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles'),
    schema='core'
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role_id'], unique=False, schema='core')
    op.create_index('ix_user_roles_user', 'user_roles', ['user_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_user', table_name='user_roles', schema='core')
    op.drop_index('ix_user_roles_role', table_name='user_roles', schema='core')
    op.drop_table('user_roles', schema='core')
    op.drop_index('ix_files_entity', table_name='files', schema='core')
    op.drop_index(op.f('ix_core_files_updated_by'), table_name='files', schema='core')
    op.drop_index(op.f('ix_core_files_deleted_by'), table_name='files', schema='core')
    op.drop_index(op.f('ix_core_files_created_by'), table_name='files', schema='core')
    op.drop_table('files', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_updated_by'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_deleted_by'), table_name='audit_logs', schema='core')
    op.drop_index(op.f('ix_core_audit_logs_created_by'), table_name='audit_logs', schema='core')
    op.drop_index('ix_audit_logs_table', table_name='audit_logs', schema='core')
    op.drop_index('ix_audit_logs_record', table_name='audit_logs', schema='core')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs', schema='core')
    op.drop_table('audit_logs', schema='core')
    op.drop_index(op.f('ix_core_users_username'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_updated_by'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_person_id'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_deleted_by'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_created_by'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index('ix_role_permissions_role', table_name='role_permissions', schema='core')
    op.drop_index('ix_role_permissions_permission', table_name='role_permissions', schema='core')
    op.drop_table('role_permissions', schema='core')
    op.drop_index('ix_people_document', table_name='people', schema='core')
    op.drop_index(op.f('ix_core_people_updated_by'), table_name='people', schema='core')
    op.drop_index(op.f('ix_core_people_email'), table_name='people', schema='core')
    op.drop_index(op.f('ix_core_people_deleted_by'), table_name='people', schema='core')
    op.drop_index(op.f('ix_core_people_created_by'), table_name='people', schema='core')
    op.drop_table('people', schema='core')
    op.drop_index(op.f('ix_core_roles_updated_by'), table_name='roles', schema='core')
    op.drop_index(op.f('ix_core_roles_deleted_by'), table_name='roles', schema='core')
    op.drop_index(op.f('ix_core_roles_created_by'), table_name='roles', schema='core')
    op.drop_index(op.f('ix_core_roles_code'), table_name='roles', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_index(op.f('ix_core_permissions_updated_by'), table_name='permissions', schema='core')
    op.drop_index(op.f('ix_core_permissions_deleted_by'), table_name='permissions', schema='core')
    op.drop_index(op.f('ix_core_permissions_created_by'), table_name='permissions', schema='core')
    op.drop_index(op.f('ix_core_permissions_code'), table_name='permissions', schema='core')
    op.drop_table('permissions', schema='core')
    op.drop_index(op.f('ix_core_genders_updated_by'), table_name='genders', schema='core')
    op.drop_index(op.f('ix_core_genders_deleted_by'), table_name='genders', schema='core')
    op.drop_index(op.f('ix_core_genders_created_by'), table_name='genders', schema='core')
    op.drop_index(op.f('ix_core_genders_code'), table_name='genders', schema='core')
    op.drop_table('genders', schema='core')
    op.drop_index(op.f('ix_core_document_types_updated_by'), table_name='document_types', schema='core')
    op.drop_index(op.f('ix_core_document_types_deleted_by'), table_name='document_types', schema='core')
    op.drop_index(op.f('ix_core_document_types_created_by'), table_name='document_types', schema='core')
    op.drop_index(op.f('ix_core_document_types_code'), table_name='document_types', schema='core')
    op.drop_table('document_types', schema='core')
    # ### end Alembic commands ###
