"""create organization settings and themes

Revision ID: cac2f9f1c251
Revises: 1caa5fe27ba0
Create Date: 2026-07-15 18:13:47.168337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac2f9f1c251'
down_revision: Union[str, Sequence[str], None] = '1caa5fe27ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('sidebar_background_color', sa.String(length=20), nullable=False),
    sa.Column('sidebar_foreground_color', sa.String(length=20), nullable=False),
    sa.Column('topbar_background_color', sa.String(length=20), nullable=False),
    sa.Column('topbar_foreground_color', sa.String(length=20), nullable=False),
    sa.Column('card_header_background_color', sa.String(length=20), nullable=False),
    sa.Column('card_header_foreground_color', sa.String(length=20), nullable=False),
    sa.Column('table_header_background_color', sa.String(length=20), nullable=False),
    sa.Column('table_header_foreground_color', sa.String(length=20), nullable=False),
    sa.Column('border_color', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('type'),
    schema='core'
    )
    op.create_index(op.f('ix_core_themes_created_by'), 'themes', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_themes_deleted_by'), 'themes', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_themes_updated_by'), 'themes', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_themes_is_default', 'themes', ['is_default'], unique=False, schema='core')
    op.create_index('ix_themes_type', 'themes', ['type'], unique=False, schema='core')
    op.create_table('organization_settings',
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('organization_abbreviation', sa.String(length=100), nullable=True),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('system_abbreviation', sa.String(length=100), nullable=True),
    sa.Column('logo_id', sa.UUID(), nullable=True),
    sa.Column('favicon_id', sa.UUID(), nullable=True),
    sa.Column('login_background_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('login_message', sa.String(length=300), nullable=True),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['favicon_id'], ['core.files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['login_background_id'], ['core.files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logo_id'], ['core.files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theme_id'], ['core.themes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_organization_settings_created_by'), 'organization_settings', ['created_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_organization_settings_deleted_by'), 'organization_settings', ['deleted_by'], unique=False, schema='core')
    op.create_index(op.f('ix_core_organization_settings_updated_by'), 'organization_settings', ['updated_by'], unique=False, schema='core')
    op.create_index('ix_organization_settings_theme_id', 'organization_settings', ['theme_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organization_settings_theme_id', table_name='organization_settings', schema='core')
    op.drop_index(op.f('ix_core_organization_settings_updated_by'), table_name='organization_settings', schema='core')
    op.drop_index(op.f('ix_core_organization_settings_deleted_by'), table_name='organization_settings', schema='core')
    op.drop_index(op.f('ix_core_organization_settings_created_by'), table_name='organization_settings', schema='core')
    op.drop_table('organization_settings', schema='core')
    op.drop_index('ix_themes_type', table_name='themes', schema='core')
    op.drop_index('ix_themes_is_default', table_name='themes', schema='core')
    op.drop_index(op.f('ix_core_themes_updated_by'), table_name='themes', schema='core')
    op.drop_index(op.f('ix_core_themes_deleted_by'), table_name='themes', schema='core')
    op.drop_index(op.f('ix_core_themes_created_by'), table_name='themes', schema='core')
    op.drop_table('themes', schema='core')
    # ### end Alembic commands ###
